spring:
  application:
    name: flashcart-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/flashcart_db
    username: postgres
    password: "Asdxxc23@"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: flashcart-super-secret-key-for-jwt-token-generation
  expiration: 86400000